[en]
  title = "Hugo Zzo Theme"
  languageName = "English"
  weight = 1
  languageDirection = "ltr"
  contentdir = "content/en"

[ko]
  title = "Hugo Zzo Theme"
  languageName = "한국어"
  weight = 2
  languageDirection = "ltr"
  contentdir = "content/ko"
