name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hugo-version:
          - 'latest'
          - '0.65.3'  # '0.65.0'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: true

      - name: Run Hugo
        working-directory: exampleSite
        run: |
          mkdir -p themes
          ln -s ../.. themes/zzo
          hugo